#!/bin/sh

perc="$(acpi | awk -F ', ' '{print $2}')"
numperc=${perc::-1}

charging="$(acpi | awk -F ', ' '{print $1}')"
if [ "$charging" = "Battery 0: Discharging" ]; then
    chs=""
else
    chs=""
fi

if (( numperc > 80 )); then
    echo "$chs $perc"
elif (( numperc > 40 )); then
    echo "$chs $perc"
elif (( numperc > 20 )); then
    echo "$chs $perc"
else
    echo "$chs $perc"
fi

